var searchData=
[
  ['c0_5fm_5fs',['c0_m_s',['../classCDX_1_1File.html#aa0bf9167da7f55469dc954e6f6470c45',1,'CDX::File']]],
  ['call_5fmake_5fpower_5faxes',['call_make_power_axes',['../group__python__tools__cdx__display.html#ga2c5e1083b33b70310788aea4c6e17b09',1,'cdx-display']]],
  ['cdx',['CDX',['../namespaceCDX.html',1,'']]],
  ['cdx_2dcompute_2dmultipath_2dspread_2dand_2denergy',['cdx-compute-multipath-spread-and-energy',['../cdx-compute-multipath-spread-and-energy.html',1,'']]],
  ['cdx_2dcompute_2dmultipath_2dto_2dline_2dof_2dsight_2dcomponents_2dpower_2dratio',['cdx-compute-multipath-to-line-of-sight-components-power-ratio',['../cdx-compute-multipath-to-line-of-sight-components-power-ratio.html',1,'']]],
  ['cdx_2dcompute_2dpower_2ddelay_2dprofile',['cdx-compute-power-delay-profile',['../cdx-compute-power-delay-profile.html',1,'']]],
  ['cdx_2dconvert_2dcontinuous_2dto_2ddiscrete_2ecpp',['cdx-convert-continuous-to-discrete.cpp',['../cdx-convert-continuous-to-discrete_8cpp.html',1,'']]],
  ['cdx_2ddisplay',['cdx-display',['../cdx-display.html',1,'']]],
  ['cdx_2dplot_2ddiscrete_2ddelay_2dfile',['cdx-plot-discrete-delay-file',['../cdx-plot-discrete-delay-file.html',1,'']]],
  ['cdx_20file_20format',['CDX File Format',['../cdx_file_format.html',1,'']]],
  ['cdxdisplaywindows',['CDXDisplayWindows',['../classcdx-display_1_1CDXDisplayWindows.html',1,'cdx-display']]],
  ['cdxreadfile',['CDXReadFile',['../classCDXReadFile.html',1,'']]],
  ['cdxreadfile_2em',['CDXReadFile.m',['../CDXReadFile_8m.html',1,'']]],
  ['cdxwritefile',['CDXWriteFile',['../classCDXWriteFile.html',1,'']]],
  ['cdxwritefile_2em',['CDXWriteFile.m',['../CDXWriteFile_8m.html',1,'']]],
  ['channellink',['ChannelLink',['../classcdx-display_1_1ChannelLink.html',1,'cdx-display']]],
  ['cir_5frate_5fhz',['cir_rate_Hz',['../classCDX_1_1File.html#ae29fbca8f0a4491398d7852cf49b557b',1,'CDX::File']]],
  ['cir_5ft',['cir_t',['../structCDX_1_1cir__t.html',1,'CDX']]],
  ['combobox_5findex_5fchanged',['combobox_index_changed',['../classcdx-display_1_1ChannelLink.html#a5da5c09697f185c202c365fd0d48a226',1,'cdx-display::ChannelLink']]],
  ['component_5ftypes_5ft',['component_types_t',['../namespaceCDX.html#aa648f6ec7bc4765b4c95c5a4679fe3a0',1,'CDX']]],
  ['components',['components',['../structCDX_1_1cir__t.html#a0d0ad1aaa983c5885f3d46a5306c3c34',1,'CDX::cir_t']]],
  ['components_5ft',['components_t',['../namespaceCDX.html#a11c27b1cbad0f9d29b5ef874c81ed798',1,'CDX']]],
  ['compute_5fmultipath_5fspread',['compute_multipath_spread',['../classcdx_1_1ReadContinuousDelayFile_1_1ReadContinuousDelayFile.html#a1304c669ca15a4792064697eb09d7710',1,'cdx::ReadContinuousDelayFile::ReadContinuousDelayFile']]],
  ['compute_5fnof_5fcomponents',['compute_nof_components',['../classcdx_1_1ReadContinuousDelayFile_1_1ReadContinuousDelayFile.html#a7ae5562ec3eadadf3c3aa2deaf4e860d',1,'cdx::ReadContinuousDelayFile::ReadContinuousDelayFile']]],
  ['compute_5fpower',['compute_power',['../classcdx_1_1ReadContinuousDelayFile_1_1ReadContinuousDelayFile.html#adccd683277ca9656e81d75ba424e416f',1,'cdx::ReadContinuousDelayFile::ReadContinuousDelayFile']]],
  ['convert_5fcontinuous_5fto_5fdiscrete_5fdelay_2em',['convert_continuous_to_discrete_delay.m',['../convert__continuous__to__discrete__delay_8m.html',1,'']]],
  ['cpp_5fexamples',['Cpp_examples',['../group__cpp__examples.html',1,'']]],
  ['c_2b_2b_20implementation_20of_20the_20cdx_20interface',['C++ Implementation of the CDX Interface',['../group__cpp__implementation.html',1,'']]],
  ['cdx_20tools_20written_20in_20c_2b_2b',['CDX Tools written in C++',['../group__cpp__tools.html',1,'']]],
  ['cdx_2dconvert_2dcontinuous_2dto_2ddiscrete',['cdx-convert-continuous-to-discrete',['../group__cpp__tools__cdx__convert__continuous__to__discrete.html',1,'']]],
  ['create_5fgroup',['create_group',['../classCDX_1_1WriteFile.html#a66090dce07c82e145aa5f3c156cb334b',1,'CDX::WriteFile']]],
  ['create_5fnew_5fhdf5_5ffile_5fcontinuous_5fdelay_2em',['create_new_hdf5_file_continuous_delay.m',['../create__new__hdf5__file__continuous__delay_8m.html',1,'']]],
  ['create_5freference_5fdelays_5fdataset',['create_reference_delays_dataset',['../classCDX_1_1WriteFile.html#a88bf6182758df9915ee1f8f9594f1c3f',1,'CDX::WriteFile']]],
  ['create_5fnew_5fhdf5_5ffile_5fcontinuous_5fdelay',['create_new_hdf5_file_continuous_delay',['../group__matlab__example__create__new__hdf5__file__continuous__delay.html',1,'']]],
  ['cdx_20tools_20written_20in_20matlab',['CDX Tools written in Matlab',['../group__matlab__tools.html',1,'']]],
  ['convert_5fcontinuous_5fto_5fdiscrete_5fdelay',['convert_continuous_to_discrete_delay',['../group__matlab__tools__convert__continuous__to__discrete__delay.html',1,'']]],
  ['cdx_20tools_20written_20in_20python',['CDX Tools written in Python',['../group__python__tools.html',1,'']]],
  ['cdx_2dcompute_2dmultipath_2dspread_2dand_2denergy',['cdx-compute-multipath-spread-and-energy',['../group__python__tools__cdx__compute__multipath__spread__and__energy.html',1,'']]],
  ['cdx_2dcompute_2dmultipath_2dto_2dline_2dof_2dsight_2dcomponents_2dpower_2dratio',['cdx-compute-multipath-to-line-of-sight-components-power-ratio',['../group__python__tools__cdx__compute__multipath__to__line__of__sight__components__power__ratio.html',1,'']]],
  ['cdx_2dcompute_2dpower_2ddelay_2dprofile',['cdx-compute-power-delay-profile',['../group__python__tools__cdx__compute__power__delay__profile.html',1,'']]],
  ['cdx_2ddisplay',['cdx-display',['../group__python__tools__cdx__display.html',1,'']]],
  ['cdx_2dplot_2ddiscrete_2ddelay_2dfile',['cdx-plot-discrete-delay-file',['../group__python__tools__cdx__plot__discrete__delay__file.html',1,'']]]
];
